[package]
name = "service-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serenity = "0.12.4"
tokio = { version = "1.48.0", features = ["macros", "process", "rt-multi-thread", "sync"] }
toml = "0.9.10"
